name: New job
on: [push]

jobs:
  New-job-fixed:
    runs-on: Windows-latest
    steps:
      - name: JOB
        run: echo "Preksha you will be in new company soon with 10 lakh package - Efforts for Family"

      - name: Multiline command
        run:
            npm -v
            node -v  

      - name: Python command
        run: |
          import platform
          print(platform.processor())

        shell: python  
